language: R
cache: packages
warnings_are_errors: true
r_check_args: --as-cran --run-donttest

branches:
  only:
    - master

before_deploy:
  # Install a previous version of `pkgdown` and its dependencies, which appears more stable.
  - Rscript -e 'install.packages(c("fs", "highlight", "httr", "memoise", "openssl", "rmarkdown", "whisker", "xml2", "purrr"))'
  - Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/pkgdown/pkgdown_1.5.1.tar.gz", repos = NULL, type = "source")'
  # Install packages for the vignettes
  - Rscript -e 'install.packages("ggplot2")'
  - Rscript -e 'install.packages(getwd(), repos = NULL, type = "source")'
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  local_dir: docs/
  skip_cleanup: true
  github-token: $GH_TOKEN
