language: R
cache: packages
warnings_are_errors: true
r_check_args: --as-cran --run-donttest

branches:
  only:
    - master

# before_deploy:
#   - cp releases/CHANGELOG.md .
#   - Rscript -e 'install.packages("pkgdown");
#   - Rscript -e 'install.packages(getwd(), repos = NULL, type = "source");
#   - pkgdown::build_site()'

# deploy:
#   provider: pages
#   local_dir: docs/
#   skip_cleanup: true
#   github-token: $GH_TOKEN
